inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 135

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/ModuleLength:
  Max: 500

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 110

Metrics/AbcSize:
  Max: 115

Metrics/CyclomaticComplexity:
  Max: 35

Metrics/PerceivedComplexity:
  Max: 35

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: true

Style/AndOr:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

